### ISSUE TITLE
Simulation not working

### ISSUE THREAD

**Issue by Saverio976** [COOK1EK1W1/gridmas-tree#1]
Hello,

When I run it on linux (Arch Linux), the simulation window open but nothing is shown on it.

I made it works by moving the SimTree.setup_visualisation call inside a function that is called one time inside the PixelDriver.run function.

Maybe it is the initialization in the main process, then creating a process with this state that break it ?

Anyway, here are the changes I made to make it works:

```diff
diff --git a/backend/pixel_driver/pixel_driver.py b/backend/pixel_driver/pixel_driver.py
index b8e0bc7..57d2b78 100644
--- a/backend/pixel_driver/pixel_driver.py
+++ b/backend/pixel_driver/pixel_driver.py
@@ -13,7 +13,11 @@ class PixelDriver(ABC):
         while not self.queue.empty():
             self.queue.get()
 
+    def init(self):
+        return
+
     def run(self):
+        self.init()
         cur_fps = 45
         start_time = time.perf_counter()
 
diff --git a/backend/pixel_driver/sim_tree.py b/backend/pixel_driver/sim_tree.py
index d59301e..8b9188c 100644
--- a/backend/pixel_driver/sim_tree.py
+++ b/backend/pixel_driver/sim_tree.py
@@ -13,6 +13,7 @@ class SimTree(PixelDriver):
         self.buffer = [0 for _ in range(len(coords))]
         self.queue = queue
 
+    def init(self):
         self.setup_visualisation()
 
     def draw(self, frame: list[int]):
```

I don't have something to test if the changes breaks something with the real LED.

Let me know if you want me to make a pull requests.

Kindly

**Comment by COOK1EK1W1** [comment]
I've added your changes to a fix-linux branch, there was a person at the session on tuesday which i think was having the same issue on ubuntu, will test and pull if its fine :)

**Comment by COOK1EK1W1** [comment]
just added the fix :)
